#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '201':
        pose: crazy00
        pose2d: crazy00/2d
        odom: crazy00/Odom
        tf: tf
        child_frame_id: crazy00
        parent_frame_id: world
optitrack_config:
        multicast_address: 239.255.42.99
        command_port: 1510
        data_port: 1511
        enable_optitrack: true
